name: Test compatibility on macOS with venv/MacPorts

on:
  schedule:
    - cron: "0 6 * * 0"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:

    - name: Install MacPorts
      uses: melusina-org/setup-macports@v1
      id: macports

    - name: Install dependencies
      run: |
        sudo port install gcc13 python314 pkgconfig curl gpatch gnutar unzip gzip bzip2 xz perl5 gmake cmake mpich-gcc13 gsl fftw-3 gmp mpfr hdf5 netcdf netcdf-fortran qhull healpix-cxx openblas lapack zlib
        sudo port select --set gcc mp-gcc13
        sudo port select --set python3 python314

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Create virtualenv
      run: |
        python3 -m venv venv
        . venv/bin/activate && python3 -m pip install pip wheel pytest

    - name: Print debug output
      run: |
        . venv/bin/activate && ./setup
        echo "config.mk:"
        cat support/config.mk
        echo "config.log:"
        cat support/config.log

    - name: Build everything we can
      run: |
        . venv/bin/activate && ./setup install all

    - name: Ensure we test only the installed packages
      run: . venv/bin/activate && ./setup distclean

    - name: Test all
      run: . venv/bin/activate && ./setup test all

    - name: Archive build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os }}
        path: ${{ github.workspace }}/support/logs/
        if-no-files-found: warn
